@startuml
together {
class Galaxy {
-_name : string
-_systems : List<SolarSystem>
-_type : string
+Name : string
+Systems : IList<SolarSystem>
+Type : string
+Add() : void
+Remove() : bool
}

class SolarSystem {
-name : string
-bodies : List<CelestialBodyWithCore>
+Bodies : IList<CelestialBodyWithCore>
+Name : string
+Add() : void
-AddBody() : void
-AddStar() : void
+Remove() : void
}
}

abstract class CelestialBody {
#_mass : double
#_name : string
#_radius : double
#EarthMass : double
#SolarMass : double
+Area : double
+Density : double
+Mass : double
+Name : string
+Radius: double
+Volume : double
-CalculateArea() : double
-CalculateDensity() : double
-CalculateVolume() : double
+CompareTo() : int
+Equals() : bool
+GetHashCode() : int
+GetLargest() : CelestialBody
+GetMostDense() : CelestialBody
}

abstract class CelestialBodyWithCore extends CelestialBody {
#_coreSize : double
+Core : double
+CoreSize : double
-CalculateCore() : double
}

together {
class Star extends CelestialBodyWithCore {
-_corona : double
+Corona : double
}

class Planet extends CelestialBodyWithCore {
-_moons : List<Moon>
+Moons : IList<Moon>
+Add() : void
-Remove() : bool
}

class Moon extends CelestialBody {
}
}

Planet "1" *-- "N" Moon
SolarSystem "1" *-up- "N" Planet
SolarSystem "1" *-up- "3" Star
Galaxy "1" *-left- "N" SolarSystem
@enduml