@startuml
class Galaxy extends CelestialObject {
}

class SolarSystem extends CelestialObject {
}

abstract class CelestialBody extends CelestialObject{
}

abstract class CelestialBodyWithCore extends CelestialBody {
}

class Star extends CelestialBodyWithCore {
}

class Planet extends CelestialBodyWithCore {
}

class Moon extends CelestialBody {
}

Planet "1" *-- "N" Moon
Moon o-- Planet
SolarSystem "1" *-- "N" Planet
Planet o-- SolarSystem
SolarSystem "1" *-- "3" Star
Star o-- SolarSystem
Galaxy "1" *-- "N" SolarSystem
SolarSystem o-- Galaxy
@enduml